---
- name: Clone the cache in Digital Ocean for content fetcher RapidAPI
  hosts: do
  tasks:
    - name: Get the container id
      ansible.builtin.command:
        cmd: docker ps --filter name=srv-captain--rapidapi-content-fetcher -q
      register: out

    - name: Print the container id
      debug:
        msg: "Container id is {{out.stdout}}"

    - name: Get the volume path for the container
      ansible.builtin.command:
        cmd: "docker inspect {{out.stdout}}"
      register: out

    - debug: var=out.stdout