---
- name: Scrape link in Digital Ocean for content fetcher RapidAPI
  hosts: do
  tasks:
    - name: Get the container id
      ansible.builtin.command:
        cmd: docker ps --filter name=srv-captain--rapidapi-content-fetcher -q
      register: out

    - name: Print the container id
      debug:
        msg: "Container id is {{out.stdout}}"

    - name: Run scrape command in DO
      ansible.builtin.command:
        cmd: "docker exec -it {{out.stdout}} /bin/bash -c './command.sh -s -l={{vars.link}}'"
      register: out

    - debug: var=out.stdout_lines